### ISSUE TITLE
Lexicographical / Static Output

### ISSUE THREAD

**Issue by amygd555** [doksu/TA-jsontools#2]
Thank you for a great tool.

Have you considered implementing an option for static ordering (such as lexicographical order) of keys? I know the JSON spec deems key order as irrelevant but this could be a useful function for example when throttling an alert per JSON Object where you would need a consistent results over searches to successfully remove duplicates. 

This app solves this https://splunkbase.splunk.com/app/3237/ but you might want to avoid app overload, with my clunky solution serving as example:

`| makeresults
| eval a = "a"
| eval b = "b"
| eval c = "c"
|  mkjson
| jsonformat order=sort _raw as json_formatted ##secondary app
| fields json_formatted
| eval hash = sha256(json_formatted) ##for cleaner throttling`

Br, thanks

**Comment by doksu** [comment]
Thanks very much for raising this @amygd555 

I've just commited 8d27a011f3b5b68d59ae6034a8ddb77bdea3365c, which appears to work well. Would you mind testing to ensure it works as expected?

**Comment by amygd555** [comment]
Works well in my tests @doksu 
Apologies for the late reply and thank you for the quick fix. I'll await the updated app on splunkbase before closing.
